language:
  - python

python:
  - "2.7"

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

install:
  # Info about OS
  - uname -a

  # Info about Python
  - which python
  - python --version

  - which pip
  - pip --version

  - pip install --user -r docs/requirements.txt

script:
  - cd docs
  - sphinx-build -v -W . _build
  - sphinx-build -b spelling . _spelling
